-- 테이블 복사 방법 (테이블 + 데이터)
-- 1. 테이블 + 데이터 복사.
CREATE TABLE EMPLOYEE_COPY AS SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEE_COPY;

-- 2. 구조만 복사. : 위와 반대. 제약조건과 인덱스를 그대로 가져오지만 데이터는 0건.
CREATE TABLE EMPLOYEE_COPY2 LIKE EMPLOYEES;
SELECT * FROM EMPLOYEE_COPY2;

-- 3. 완전 복사.
CREATE TABLE EMPLOYEE_COPY3 LIKE EMPLOYEES;
INSERT INTO EMPLOYEE_COPY3 SELECT * FROM EMPLOYEES;
SELECT * FROM EMPLOYEE_COPY3;