-- 데이터베이스 생성 (이름)
-- 사용 명령어
-- 테이블 생성 , 컬럼 수정 , 데이터 조회 및 삽입 실습.
CREATE DATABASE DB_EX;
CREATE TABLE DB1(
	USER_ID INT PRIMARY KEY ,
    USER_NAME VARCHAR(10) NOT NULL,
    ADDR VARCHAR(10) 
);

INSERT INTO DB1 VALUES(1 , '이' , '서울');
INSERT INTO DB1(USER_ID , USER_NAME) VALUES(2 , '김' );

ALTER TABLE DB1 ADD COLUMN A INT NOT NULL ;

DELETE FROM DB1;

SELECT * FROM DB1;