SELECT * FROM EMPLOYEE_COPY3;
DESC EMPLOYEE_COPY3;

SHOW INDEX FROM EMPLOYEE_COPY3;

SELECT * FROM EMPLOYEE_COPY3
WHERE GENDER = 'M';

-- GENDER에 인덱스 추가.
ALTER TABLE employee_copy3 ADD INDEX IDX_GENDER(GENDER);

SELECT * FROM EMPLOYEE_COPY3
WHERE FIRST_NAME = 'Georgi';

SELECT * FROM EMPLOYEE_COPY3
WHERE EMP_NO = 15689;

-- 실습. 인덱스 키 직접 생성 (실행계획 확인해서 결과 비교).
-- 단일 인덱스.
ALTER TABLE employee_copy3 ADD INDEX IDX_LAST_NAME(LAST_NAME);
DROP INDEX IDX_LAST_NAME ON employee_copy3;

-- 복합 인덱스.
CREATE INDEX IDX_FIRST_LAST_NAME ON EMPLOYEE_COPY3(FIRST_NAME , LAST_NAME);


-- 복합 인덱스를 사용하려면 검색할때도 복합시킨 컬럼을 모두 사용해야함.
SELECT * FROM EMPLOYEE_COPY3
WHERE FIRST_NAME = 'Sumant';
