DROP DATABASE IF EXISTS bank;
CREATE DATABASE bank;
USE bank;

CREATE TABLE accounts (
    account_id INT PRIMARY KEY,
    name VARCHAR(50),
    balance INT NOT NULL
);

INSERT INTO accounts VALUES
    (1, 'Alice', 100000),
    (2, 'Bob', 50000);

SELECT * FROM accounts;

-- 수동으로 트랜잭션 시작.
START TRANSACTION;

UPDATE ACCOUNTS SET BALANCE = BALANCE - 30000
WHERE ACCOUNT_ID = 1;

UPDATE ACCOUNTS SET BALANCE = BALANCE + 30000
WHERE ACCOUNT_ID = 2;

UPDATE ACCOUNTS SET BALANCE = NULL
WHERE ACCOUNT_ID = 2;

-- COMMIT;
-- ROLLBACK ;

SELECT '롤백 전' AS 시점 , ACCOUNT_ID , BALANCE FROM ACCOUNTS
WHERE ACCOUNT_ID = 1;

-- 오류 발생하더라도 자동 취소는 안됨. --> 직접 ROLLBACK해야함.
ROLLBACK;
SELECT '롤백 후' AS 시점 , ACCOUNT_ID , BALANCE FROM ACCOUNTS
WHERE ACCOUNT_ID = 1;

-- 잔액 부족시 처리 방법
START transaction;

UPDATE ACCOUNTS SET BALANCE = BALANCE - 200000
WHERE ACCOUNT_ID = 1 AND BALANCE >= 200000;

-- 적용된 ROW COUNT 확인 명령어.
SELECT ROW_COUNT() AS '변경된 행수';

SELECT * FROM ACCOUNTS;
