-- INNER JOIN 연습.
SELECT P.* , T.PASSPORT_NUMBER 
FROM TB_PERSON P INNER JOIN tb_passport T ON T.PERSON_ID = P.PERSON_ID;

-- 일부러 안맞는 조건 매칭.
SELECT P.* , T.PASSPORT_NUMBER 
FROM TB_PERSON P INNER JOIN tb_passport T ON T.PASSPORT_NUMBER = P.NAME;


SELECT * FROM TB_PERSON;
SELECT * FROM TB_PASSPORT;





SELECT E.EMP_NO , E.HIRE_DATE , D.FROM_DATE 
FROM EMPLOYEE_COPY3 E INNER JOIN DEPT_MANAGER D ON E.EMP_NO = D.EMP_NO
WHERE HIRE_DATE >= '19900101';


SELECT D.DEPT_NO , D.EMP_NO , E.FIRST_NAME , E.LAST_NAME  
FROM DEPT_MANAGER D LEFT JOIN EMPLOYEE_COPY3 E ON D.EMP_NO ;
		   

                
                
SELECT  E.FIRST_NAME , E.LAST_NAME , E.HIRE_DATE
FROM EMPLOYEE_COPY3 E LEFT JOIN EMPLOYEE_COPY3 EE ON E.HIR;

SELECT E.FIRST_NAME FROM EMPLOYEES E 
JOIN EMPLOYEES M ON E.GENDER = M.GENDER;	
                
select e.first_name , e.hire_date
from employee_copy3 e inner join employee_copy3 m on e.hire_date = m.hire_date
and e.emp_no < m.emp_no;                
                
SELECT * FROM EMPLOYEE_COPY3 
WHERE FIRST_NAME = 'Fan';	
SELECT * FROM DEPT_EMP;
SELECT * FROM DEPT_MANAGER;
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEE_COPY3;
SELECT * FROM EMPLOYEEs;
SELECT * FROM TITLES;
SELECT * FROM SALARIES;